/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.snake_and_ladder;

public class App {
    public static void main(String[] args) {
        new Game().startSnakeAndLadder();
    }
}
